#ifndef THINGPROPERTIES_H
#define THINGPROPERTIES_H

// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "credentials.h"

const char SSID[] = SECRET_SSID;         // Network SSID (name)
const char PASS[] = SECRET_OPTIONAL_PASS;// Network password (use for WPA, or use as key for WEP)

float frequency = 50;
float xrms = 1;
float lowerFrequencyThreshold = 49.9;
float upperFrequencyThreshold = 50.1;
bool isFrequencyWithinThresholds = true;

void initProperties() {

    ArduinoCloud.addProperty(frequency, READ, 1 * SECONDS, NULL);
    ArduinoCloud.addProperty(xrms, READ, 1 * SECONDS, NULL);
    ArduinoCloud.addProperty(isFrequencyWithinThresholds, READ, 1 * SECONDS, NULL);
    ArduinoCloud.addProperty(lowerFrequencyThreshold, READWRITE, 1 * SECONDS, NULL);
    ArduinoCloud.addProperty(upperFrequencyThreshold, READWRITE, 1 * SECONDS, NULL);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);

#endif//THINGPROPERTIES_H
